### PR TITLE
Api improvements

### PR DESCRIPTION
**Pull request by tamir61**
I've created useQuery and useMutation hooks to have the ability to handle loading and error states in UI

@nivg1992 please run it locally before approve as I didn't try those changes (I don't have mocked data)

### CODE REVIEW

**Comment by nivg1992** [comment]
Nice!
if you want to check that for the main screen, you can create a folder structure like that
data/faces/{somename}/img.jpg
and run the Python following the documentation

I also will check that on my local env in the evening

**Comment by tamir61** [comment]
@nivg1992 I've tried to run it locally, but no luck :(

**Comment by nivg1992** [comment]
let's try by docker just
`docker run -e PF_DATA_FOLDER='/data' -p 5000:5000 -v ./data:/data nivg1992/faceplatform`

besides, it's looked great on my env, let's merge it

**Review by nivg1992 — APPROVED** [review]

**Comment by tamir61** [comment]
If everything works, merge it :)

**Pull request merged**
